jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: '16

          17

          '
    - continue-on-error: true
      env:
        BLUECOLORED_PASSWORD: ${{ secrets.BLUECOLORED_PASSWORD }}
        BLUECOLORED_USERNAME: ${{ secrets.BLUECOLORED_USERNAME }}
      name: Build with Gradle
      run: ./gradlew clean :BlueMapCore:publish :BlueMapCommon:publish
name: Publish
on:
  repository_dispatch:
    types: trigger-ga___publish.yml
